tasks:
  - command: |
      export APP_URL=`gp url 8080 | sed 's~https://~~'`
      docker-compose up
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
